---
kind: pipeline
name: test

steps:
- name: test
  image: node:16
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
  commands:
    - apt update
    - apt-get install jq -y
    - npm install
    - npm run test

volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock

trigger:
  event: [push]
---
kind: pipeline
name: tag
depends_on: [test]

clone:
  depth: 100

steps:
- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN_PUBLISH

trigger:
  event: [push]
---
kind: signature
hmac: 5b7087b7c7f704c9069e6e1b3b6b6f3694748e5ca05e3f10656bd18de21ee475

...
