---
kind: pipeline
name: test

steps:
- name: test
  image: node:24
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
  commands:
    - apt update && apt-get install -y jq
    - npm install
    - npm run test

volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock

trigger:
  event: [push]
---
kind: pipeline
name: tag
depends_on: [test]

clone:
  depth: 100

steps:
- name: release
  image: livingdocs/semantic-release:v3.0.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN_PUBLISH

trigger:
  event: [push]
---
kind: signature
hmac: 27778282c8f51ecd2f8654382138d8354a72122a36dd0f9a37092eb385295355

...
