#!/bin/bash
currentDir=$(node -e "console.log(require('path').dirname(require('fs').realpathSync('$BASH_SOURCE')))")

help () {
  >&2 echo "Usage: $0 <command>"
  >&2 echo ""
  >&2 echo "  commands for a customer release (f.e. livingdocs-service-server or livingdocs-bluewin-server):"
  >&2 echo "   tag-and-deploy-docker-image:     Tag, publish and deploy docker image to rancher"
  >&2 echo ""
  >&2 echo "  helper commands:"
  >&2 echo "   upgrade-rancher-container:       Upgrade the image of a rancher service"
  >&2 echo "   tag-publish-docker-image:        Tag and publish docker image"
  >&2 echo "   push-feat-commit:                Create and push a branch with a feat commit."
  >&2 echo ""
  exit 1
}

cmd="$1"
shift
case "$cmd" in
    upgrade-rancher-container)
        $currentDir/bin/upgrade-rancher-container
        ;;
    tag-publish-docker-image)
        $currentDir/bin/tag-publish-docker-image $*
        ;;
    tag-and-deploy-docker-image)
        $currentDir/bin/tag-and-deploy-docker-image $*
        ;;
    push-feat-commit)
        $currentDir/bin/push-feat-commit $*
        ;;
    *)
        help
        ;;
esac
