#!/bin/bash
currentDir=$(node -e "console.log(require('path').dirname(require('fs').realpathSync('$BASH_SOURCE')))")

help () {
  >&2 echo "Usage: $0 <command>"
  >&2 echo ""
  >&2 echo "  commands for a customer release (f.e. livingdocs-service-server or livingdocs-bluewin-server):"
  >&2 echo "   init-release:                    Inits a release (create release branch, updates release related files, push it to github)"
  >&2 echo "   finish-release:                  Finishes a release (add tag to last commit, push it to github)"
  >&2 echo "   tag-and-deploy-docker-image:     Tag, publish and deploy docker image to rancher"
  >&2 echo ""
  >&2 echo "  commands for a core release (f.e. livingdocs-server):"
  >&2 echo "   create-release-branch:           Creates a release branch to support older versions"
  >&2 echo ""
  >&2 echo "  helper commands:"
  >&2 echo "   upgrade-rancher-container:       Upgrade the image of a rancher service"
  >&2 echo "   tag-publish-docker-image:        Tag and publish docker image"
  >&2 echo "   push-feat-commit:                Create and push a branch with a feat commit."
  >&2 echo ""
  exit 1
}

cmd="$1"
shift
case "$cmd" in
    upgrade-rancher-container)
        $currentDir/bin/upgrade-rancher-container
        ;;
    init-release)
        $currentDir/bin/init-release $*
        ;;
    finish-release)
        $currentDir/bin/finish-release $*
        ;;
    create-release-branch)
        $currentDir/bin/create-release-branch $*
        ;;
    tag-publish-docker-image)
        $currentDir/bin/tag-publish-docker-image $*
        ;;
    tag-and-deploy-docker-image)
        $currentDir/bin/tag-and-deploy-docker-image $*
        ;;
    push-feat-commit)
        $currentDir/bin/push-feat-commit $*
        ;;
    *)
        help
        ;;
esac
